# 서버 설정
server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    uri-encoding: UTF-8

# 로그 설정
logging:
# pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss} 처리시간:%r 로그레벨:%p 파일명:%F %n 클래스명:%C 함수명:%M 라인수:%L %n 메시지 ==> %m %n%n'
  level:
#    org.springframework: DEBUG
    com.autumnia.shop: DEBUG

# 스프링 설정
spring:
  application:
    name: template
  profiles:
    active: dev
  main:
    banner-mode: off
  output:
    ansi.enabled: always
  messages:
    basename: messages

  # database
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:D:/gitroot/data/basic
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none # drop -> create -> alter  -> drop(종료)
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

# actuator 설정
managemnet:
  endpoints:
    web:
      exposure:
        include: "*"